import numpy as np
import matplotlib.pyplot as plt

# Load random numbers generated by the Fortran program
random_numbers = np.loadtxt('ran_uni.dat')

# Plot histogram to visualize the probability distribution
plt.hist(random_numbers, bins=50, density=True, alpha=0.7, color='green', edgecolor='black')

# Add labels and title
plt.xlabel('Value')
plt.ylabel('Probability Density')
plt.title('Histogram of Uniformly Distributed Random Numbers (Fortran)')

# Show the plot
plt.show()

