import numpy as np
import matplotlib.pyplot as plt

# Load random numbers generated by the Fortran program
data= np.loadtxt('ran_2b.dat')

# Plot histogram to visualize the probability distribution
plt.scatter(data[:,0],data[:,1],color="magenta")

# Add labels and title
#plt.xlabel('Value')
#plt.ylabel('Probability Density')
#plt.title('Histogram of Uniformly Distributed Random Numbers (Fortran)')

# Show the plot
plt.show()

