import numpy as np
import matplotlib.pyplot as plt

# Load random numbers generated by the Fortran program
data= np.loadtxt('c_k.dat')

# Plot histogram to visualize the probability distribution
plt.plot(data[:,0],data[:,1],color="magenta")
plt.grid()
# Add labels and title
plt.xlabel('k')
plt.ylabel('correlation value')
plt.title('k vs c_k plot')


# Show the plot
plt.show()

